package cli_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/trues/qbs/internal/cli"
)

func TestInitProvisionsIgnoredAIWorkspaceIdempotently(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	old, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(repo); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(old) })

	var firstOut, firstErr bytes.Buffer
	if err := cli.Run([]string{"init"}, &firstOut, &firstErr); err != nil {
		t.Fatal(err)
	}

	wants := []string{
		"AGENTS.md",
		"CLAUDE.md",
		filepath.Join(".codex", "agents", "implementer.toml"),
		filepath.Join(".claude", "agents", "implementer.md"),
		filepath.Join(".opencode", "agents", "implementer.md"),
		filepath.Join(".agents", "skills", "qbs", "SKILL.md"),
		filepath.Join(".claude", "skills", "qbs", "SKILL.md"),
		filepath.Join(".opencode", "skills", "qbs", "SKILL.md"),
		".research",
		".specs",
	}
	for _, name := range wants {
		if _, err := os.Stat(filepath.Join(repo, name)); err != nil {
			t.Errorf("init did not create %s: %v", name, err)
		}
	}
	for _, name := range wants[:len(wants)-2] {
		if out := runGit(t, repo, "check-ignore", "--", name); strings.TrimSpace(out) == "" {
			t.Errorf("%s is not ignored", name)
		}
	}
	if status := runGit(t, repo, "status", "--short"); status != "" {
		t.Fatalf("initialized repository has Git changes: %q", status)
	}

	agents := filepath.Join(repo, "AGENTS.md")
	if err := os.WriteFile(agents, []byte("local instructions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var secondOut, secondErr bytes.Buffer
	if err := cli.Run([]string{"init"}, &secondOut, &secondErr); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(agents)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != "local instructions\n" {
		t.Fatalf("existing AGENTS.md was overwritten: %q", data)
	}
	generated := filepath.Join(repo, ".codex", "agents", "implementer.toml")
	if err := os.WriteFile(generated, []byte("# Generated by qbs from its embedded agent catalog.\nstale generated agent\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := cli.Run([]string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	generatedData, err := os.ReadFile(generated)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(generatedData), `name = "implementer"`) {
		t.Fatalf("init did not refresh managed agent: %q", generatedData)
	}
	unmanaged := filepath.Join(repo, ".opencode", "agents", "implementer.md")
	if err := os.WriteFile(unmanaged, []byte("---\ndescription: local agent\n---\n\nKeep me.\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	unrelated := filepath.Join(repo, ".opencode", "agents", "local-only.md")
	if err := os.WriteFile(unrelated, []byte("local only\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var preserveErr bytes.Buffer
	if err := cli.Run([]string{"init"}, &bytes.Buffer{}, &preserveErr); err != nil {
		t.Fatal(err)
	}
	for path, want := range map[string]string{unmanaged: "Keep me.", unrelated: "local only"} {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), want) {
			t.Errorf("init changed unmanaged agent %s: %q", path, data)
		}
	}
	if !strings.Contains(preserveErr.String(), "preserving unmanaged local agent") {
		t.Errorf("init did not warn about the unmanaged same-named agent: %q", preserveErr.String())
	}
	excludeData, err := os.ReadFile(filepath.Join(repo, ".git", "info", "exclude"))
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range []string{"AGENTS.md", "CLAUDE.md", ".agents/skills/", ".claude/agents/", ".claude/skills/", ".codex/agents/", ".opencode/agents/", ".opencode/skills/", ".research/", ".specs/"} {
		if count := strings.Count(string(excludeData), entry); count != 1 {
			t.Errorf("exclude entry %q occurs %d times", entry, count)
		}
	}
}

func TestInitPreflightsFilesystemConflictsBeforeChangingExcludes(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	exclude := filepath.Join(repo, ".git", "info", "exclude")
	before, err := os.ReadFile(exclude)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(filepath.Join(repo, "AGENTS.md"), 0o755); err != nil {
		t.Fatal(err)
	}

	var out, errOut bytes.Buffer
	err = runInDirectory(repo, []string{"init"}, &out, &errOut)
	if err == nil || !strings.Contains(err.Error(), "not a regular file, but a file is required") {
		t.Fatalf("conflict error = %v", err)
	}
	after, err := os.ReadFile(exclude)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != string(before) {
		t.Fatalf("init changed excludes despite preflight failure")
	}
}

func TestInitRejectsTrackedAIFileBeforeChangingExcludes(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	runGit(t, repo, "config", "user.email", "qbs-tests@example.invalid")
	runGit(t, repo, "config", "user.name", "QBS Tests")
	if err := os.WriteFile(filepath.Join(repo, "AGENTS.md"), []byte("tracked instructions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	runGit(t, repo, "add", "AGENTS.md")
	runGit(t, repo, "commit", "-qm", "track agent instructions")
	exclude := filepath.Join(repo, ".git", "info", "exclude")
	before, err := os.ReadFile(exclude)
	if err != nil {
		t.Fatal(err)
	}

	err = runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil || !strings.Contains(err.Error(), "tracked") || !strings.Contains(err.Error(), "AGENTS.md") {
		t.Fatalf("error = %v", err)
	}
	after, err := os.ReadFile(exclude)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != string(before) {
		t.Fatal("init changed excludes despite tracked AI file")
	}
}

func TestProvisionPreparesAnExistingExternalWorktree(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	runGit(t, repo, "config", "user.email", "qbs-tests@example.invalid")
	runGit(t, repo, "config", "user.name", "QBS Tests")
	if err := os.WriteFile(filepath.Join(repo, "README.md"), []byte("fixture\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	runGit(t, repo, "add", "README.md")
	runGit(t, repo, "commit", "-qm", "fixture")
	worktree := filepath.Join(filepath.Dir(repo), filepath.Base(repo)+"-external")
	runGit(t, repo, "worktree", "add", "-qb", "external", worktree)

	var out, errOut bytes.Buffer
	if err := cli.Run([]string{"provision", worktree}, &out, &errOut); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{
		"AGENTS.md", "CLAUDE.md", ".research", ".specs",
		filepath.Join(".codex", "agents", "implementer.toml"),
		filepath.Join(".claude", "agents", "implementer.md"),
		filepath.Join(".opencode", "agents", "implementer.md"),
	} {
		if _, err := os.Stat(filepath.Join(worktree, name)); err != nil {
			t.Errorf("provision did not create %s: %v", name, err)
		}
	}
	if status := runGit(t, worktree, "status", "--short"); status != "" {
		t.Fatalf("provisioned worktree has Git changes: %q", status)
	}
	if !strings.Contains(out.String(), "Provisioned Git worktree") {
		t.Fatalf("provision output = %q", out.String())
	}
}

func runGit(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
	}
	return string(out)
}
