package cli_test

import (
	"bytes"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/trues/qbs/internal/cli"
	"github.com/trues/qbs/internal/templates"
)

func TestInitProvisionsIgnoredAIWorkspaceIdempotently(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	old, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(repo); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(old) })

	var firstOut, firstErr bytes.Buffer
	if err := cli.Run([]string{"init"}, &firstOut, &firstErr); err != nil {
		t.Fatal(err)
	}

	wants := []string{
		"AGENTS.md",
		"CLAUDE.md",
		filepath.Join(".codex", "agents", "implementer.toml"),
		filepath.Join(".claude", "agents", "implementer.md"),
		filepath.Join(".opencode", "agents", "implementer.md"),
		".research",
		".specs",
		filepath.Join("docs", "agents", "domain.md"),
		filepath.Join("docs", "agents", "issue-tracker.md"),
	}
	for _, name := range wants {
		if _, err := os.Stat(filepath.Join(repo, name)); err != nil {
			t.Errorf("init did not create %s: %v", name, err)
		}
	}
	for _, name := range wants {
		if out := runGit(t, repo, "check-ignore", "--", name); strings.TrimSpace(out) == "" {
			t.Errorf("%s is not ignored", name)
		}
	}
	if status := runGit(t, repo, "status", "--short"); status != "" {
		t.Fatalf("initialized repository has Git changes: %q", status)
	}
	for _, name := range []string{".agents/skills", ".claude/skills", ".opencode/skills"} {
		if _, err := os.Stat(filepath.Join(repo, name)); !os.IsNotExist(err) {
			t.Errorf("init created local skill directory %s: %v", name, err)
		}
	}

	localSkill := filepath.Join(repo, ".agents", "skills", "local", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(localSkill), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(localSkill, []byte("local skill\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	agents := filepath.Join(repo, "AGENTS.md")
	if err := os.WriteFile(agents, []byte("local instructions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var secondOut, secondErr bytes.Buffer
	if err := cli.Run([]string{"init"}, &secondOut, &secondErr); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(agents)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != "local instructions\n" {
		t.Fatalf("existing AGENTS.md was overwritten: %q", data)
	}
	if data, err := os.ReadFile(localSkill); err != nil || string(data) != "local skill\n" {
		t.Fatalf("existing local skill was changed: %q, %v", data, err)
	}
	generated := filepath.Join(repo, ".codex", "agents", "implementer.toml")
	if err := os.WriteFile(generated, []byte("# Generated by qbs from its embedded agent catalog.\nstale generated agent\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := cli.Run([]string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	generatedData, err := os.ReadFile(generated)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(generatedData), `name = "implementer"`) {
		t.Fatalf("init did not refresh managed agent: %q", generatedData)
	}
	unmanaged := filepath.Join(repo, ".opencode", "agents", "implementer.md")
	if err := os.WriteFile(unmanaged, []byte("---\ndescription: local agent\n---\n\nKeep me.\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	unrelated := filepath.Join(repo, ".opencode", "agents", "local-only.md")
	if err := os.WriteFile(unrelated, []byte("local only\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var preserveErr bytes.Buffer
	if err := cli.Run([]string{"init"}, &bytes.Buffer{}, &preserveErr); err != nil {
		t.Fatal(err)
	}
	for path, want := range map[string]string{unmanaged: "Keep me.", unrelated: "local only"} {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), want) {
			t.Errorf("init changed unmanaged agent %s: %q", path, data)
		}
	}
	if data, err := os.ReadFile(localSkill); err != nil || string(data) != "local skill\n" {
		t.Fatalf("existing local skill changed after repeated init: %q, %v", data, err)
	}
	if !strings.Contains(preserveErr.String(), "preserving unmanaged local agent") {
		t.Errorf("init did not warn about the unmanaged same-named agent: %q", preserveErr.String())
	}
	excludeData, err := os.ReadFile(filepath.Join(repo, ".git", "info", "exclude"))
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range []string{"AGENTS.md", "CLAUDE.md", ".agents/skills/", ".claude/agents/", ".claude/skills/", ".codex/agents/", ".opencode/agents/", ".opencode/skills/", ".research/", ".specs/", "docs/agents/"} {
		if count := strings.Count(string(excludeData), entry); count != 1 {
			t.Errorf("exclude entry %q occurs %d times", entry, count)
		}
	}
}

func TestInitUsesGitHubIssueTrackerAndPreservesEngineeringConfig(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	runGit(t, repo, "remote", "add", "origin", "git@github.com:example/project.git")

	if err := runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	tracker := filepath.Join(repo, "docs", "agents", "issue-tracker.md")
	data, err := os.ReadFile(tracker)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "GitHub Issues") {
		t.Fatalf("tracker template = %q", data)
	}
	for _, want := range []string{
		"gh issue status",
		"gh issue list",
		"gh issue view",
		"gh issue create",
		"gh issue edit",
		"gh issue comment",
		"gh issue close",
		"gh issue reopen",
	} {
		if !strings.Contains(string(data), want) {
			t.Errorf("GitHub tracker template is missing %q", want)
		}
	}
	if err := os.WriteFile(tracker, []byte("custom tracker\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	data, err = os.ReadFile(tracker)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != "custom tracker\n" {
		t.Fatalf("existing tracker was overwritten: %q", data)
	}
}

func TestInitProvisionsTriageLabelsWhenLocalTriageSkillExists(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	skill := filepath.Join(repo, ".agents", "skills", "triage")
	if err := os.MkdirAll(skill, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(skill, "SKILL.md"), []byte("triage\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(repo, "docs", "agents", "triage-labels.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, label := range []string{"needs-triage", "needs-info", "ready-for-agent", "ready-for-human", "wontfix"} {
		if !strings.Contains(string(data), label) {
			t.Errorf("triage mapping missing %q", label)
		}
	}
}

func TestInitProvisionsTriageLabelsFromGlobalSkillLocations(t *testing.T) {
	tests := []struct {
		name  string
		setup func(t *testing.T, qbsHome string)
	}{
		{
			name: "catalog",
			setup: func(t *testing.T, qbsHome string) {
				t.Setenv("QBS_SKILL_TARGETS", filepath.Join(t.TempDir(), "empty-target"))
				writeSkill(t, filepath.Join(qbsHome, "skills"), "triage")
			},
		},
		{
			name: "configured global target",
			setup: func(t *testing.T, qbsHome string) {
				target := filepath.Join(t.TempDir(), "global-skills")
				t.Setenv("QBS_SKILL_TARGETS", target)
				writeSkill(t, target, "triage")
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			repo := t.TempDir()
			qbsHome := t.TempDir()
			t.Setenv("QBS_HOME", qbsHome)
			test.setup(t, qbsHome)
			runGit(t, repo, "init", "-q")
			if err := runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
				t.Fatal(err)
			}
			if _, err := os.Stat(filepath.Join(repo, "docs", "agents", "triage-labels.md")); err != nil {
				t.Fatalf("global triage skill did not provision mapping: %v", err)
			}
		})
	}
}

func TestInitUpgradesLegacyInstructionsAndPreservesCustomizedFiles(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	legacyAgents, err := templates.Read("legacy/qbs-agents-v1.md")
	if err != nil {
		t.Fatal(err)
	}
	legacyClaude, err := templates.Read("legacy/qbs-claude-v1.md")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repo, "AGENTS.md"), legacyAgents, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repo, "CLAUDE.md"), legacyClaude, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"AGENTS.md", "CLAUDE.md"} {
		data, err := os.ReadFile(filepath.Join(repo, name))
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), "qbs-managed-instruction: v2") {
			t.Errorf("%s was not marked as current QBS instruction", name)
		}
		if !strings.Contains(string(data), "## Agent skills") {
			t.Errorf("%s was not upgraded with Agent skills", name)
		}
	}

	customAgents := []byte("# User-managed instructions\n\nKeep this exact text.\n")
	customClaude := []byte("# User-managed Claude instructions\n")
	if err := os.WriteFile(filepath.Join(repo, "AGENTS.md"), customAgents, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repo, "CLAUDE.md"), customClaude, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	for name, want := range map[string][]byte{"AGENTS.md": customAgents, "CLAUDE.md": customClaude} {
		data, err := os.ReadFile(filepath.Join(repo, name))
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(data, want) {
			t.Errorf("custom %s was overwritten: %q", name, data)
		}
	}
}

func TestInitLocalIssueTrackerTemplateDescribesFilesystemWorkflow(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	if err := runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(repo, "docs", "agents", "issue-tracker.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"local Markdown issue records",
		"List issues",
		"Create a ticket",
		"Update the issue file",
		"filesystem-only",
	} {
		if !strings.Contains(string(data), want) {
			t.Errorf("local tracker template is missing %q", want)
		}
	}
}

func TestInitPreflightsFilesystemConflictsBeforeChangingExcludes(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	exclude := filepath.Join(repo, ".git", "info", "exclude")
	before, err := os.ReadFile(exclude)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(filepath.Join(repo, "AGENTS.md"), 0o755); err != nil {
		t.Fatal(err)
	}

	var out, errOut bytes.Buffer
	err = runInDirectory(repo, []string{"init"}, &out, &errOut)
	if err == nil || !strings.Contains(err.Error(), "not a regular file, but a file is required") {
		t.Fatalf("conflict error = %v", err)
	}
	after, err := os.ReadFile(exclude)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != string(before) {
		t.Fatalf("init changed excludes despite preflight failure")
	}
}

func TestInitRejectsTrackedAIFileBeforeChangingExcludes(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-q")
	runGit(t, repo, "config", "user.email", "qbs-tests@example.invalid")
	runGit(t, repo, "config", "user.name", "QBS Tests")
	if err := os.WriteFile(filepath.Join(repo, "AGENTS.md"), []byte("tracked instructions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	runGit(t, repo, "add", "AGENTS.md")
	runGit(t, repo, "commit", "-qm", "track agent instructions")
	exclude := filepath.Join(repo, ".git", "info", "exclude")
	before, err := os.ReadFile(exclude)
	if err != nil {
		t.Fatal(err)
	}

	err = runInDirectory(repo, []string{"init"}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil || !strings.Contains(err.Error(), "tracked") || !strings.Contains(err.Error(), "AGENTS.md") {
		t.Fatalf("error = %v", err)
	}
	after, err := os.ReadFile(exclude)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != string(before) {
		t.Fatal("init changed excludes despite tracked AI file")
	}
}

func runInDirectory(dir string, args []string, stdout, stderr io.Writer) error {
	old, err := os.Getwd()
	if err != nil {
		return err
	}
	if err := os.Chdir(dir); err != nil {
		return err
	}
	defer func() { _ = os.Chdir(old) }()
	return cli.Run(args, stdout, stderr)
}

func runGit(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
	}
	return string(out)
}

func writeSkill(t *testing.T, root, name string) {
	t.Helper()
	dir := filepath.Join(root, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "SKILL.md"), []byte("triage\n"), 0o644); err != nil {
		t.Fatal(err)
	}
}
