package agents

import (
	"bytes"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// SyncGlobal renders and installs every built-in agent into each harness's
// per-user agent directory. Existing unmanaged files are preserved.
func SyncGlobal() (int, error) {
	catalog, err := Canonical()
	if err != nil {
		return 0, err
	}
	targets, err := globalAgentTargets()
	if err != nil {
		return 0, err
	}
	files, err := GenerateAll(catalog)
	if err != nil {
		return 0, err
	}
	type destinationFile struct {
		path string
		data []byte
	}
	destinations := make([]destinationFile, 0, len(files))
	for _, file := range files {
		var target string
		switch {
		case strings.HasPrefix(file.Path, ".codex/agents/"):
			target = targets[Codex]
		case strings.HasPrefix(file.Path, ".claude/agents/"):
			target = targets[Claude]
		case strings.HasPrefix(file.Path, ".opencode/agents/"):
			target = targets[OpenCode]
		}
		name := filepath.Base(file.Path)
		destination := filepath.Join(target, name)
		info, statErr := os.Lstat(destination)
		if statErr == nil {
			if !info.Mode().IsRegular() {
				return 0, fmt.Errorf("preserving non-regular agent target at %s", destination)
			}
			current, readErr := os.ReadFile(destination)
			if readErr != nil {
				return 0, fmt.Errorf("read agent target %s: %w", destination, readErr)
			}
			if !IsGenerated(current) {
				return 0, fmt.Errorf("preserving unmanaged agent file at %s", destination)
			}
		} else if !os.IsNotExist(statErr) {
			return 0, fmt.Errorf("inspect agent target %s: %w", destination, statErr)
		}
		destinations = append(destinations, destinationFile{path: destination, data: file.Data})
	}
	for _, item := range destinations {
		target := filepath.Dir(item.path)
		if err := os.MkdirAll(target, 0o755); err != nil {
			return 0, fmt.Errorf("create agent target %s: %w", target, err)
		}
		if err := writeAgentFile(item.path, item.data); err != nil {
			return 0, fmt.Errorf("sync agent to %s: %w", item.path, err)
		}
	}
	return len(destinations), nil
}

func writeAgentFile(destination string, data []byte) error {
	temp, err := os.CreateTemp(filepath.Dir(destination), ".qbs-agent-*")
	if err != nil {
		return err
	}
	defer os.Remove(temp.Name())
	if err := temp.Chmod(0o644); err != nil {
		temp.Close()
		return err
	}
	if _, err := temp.Write(data); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	return os.Rename(temp.Name(), destination)
}

func globalAgentTargets() (map[Harness]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("resolve user home: %w", err)
	}
	return map[Harness]string{
		Codex:    filepath.Join(home, ".codex", "agents"),
		Claude:   filepath.Join(home, ".claude", "agents"),
		OpenCode: filepath.Join(home, ".config", "opencode", "agents"),
	}, nil
}

const generatedMarker = "Generated by qbs from its embedded agent catalog."

// Harness identifies one supported agent configuration format.
type Harness string

const (
	Codex    Harness = "codex"
	OpenCode Harness = "opencode"
	Claude   Harness = "claude"
)

// File is one generated path relative to the repository root.
type File struct {
	Path string
	Data []byte
}

// Generate renders all agents for a harness in stable name order.
func Generate(c Catalog, harness Harness) ([]File, error) {
	if err := c.Validate(); err != nil {
		return nil, err
	}
	agents := append([]Agent(nil), c.Agents...)
	sort.Slice(agents, func(i, j int) bool { return agents[i].Name < agents[j].Name })
	files := make([]File, 0, len(agents))
	for _, agent := range agents {
		profile := c.Models[agent.Model]
		var filePath, content string
		switch harness {
		case Codex:
			filePath = path.Join(".codex", "agents", agent.Name+".toml")
			content = generateCodex(agent, profile.Codex)
		case OpenCode:
			filePath = path.Join(".opencode", "agents", agent.Name+".md")
			content = generateOpenCode(agent, profile.OpenCode)
		case Claude:
			filePath = path.Join(".claude", "agents", agent.Name+".md")
			content = generateClaude(agent, profile.Claude)
		default:
			return nil, fmt.Errorf("generate agents: unsupported harness %q", harness)
		}
		files = append(files, File{Path: filePath, Data: []byte(content)})
	}
	return files, nil
}

// IsGenerated reports whether data belongs to QBS and may be refreshed safely.
func IsGenerated(data []byte) bool {
	marker := []byte("# " + generatedMarker)
	return bytes.HasPrefix(data, marker) || bytes.HasPrefix(data, append([]byte("---\n"), marker...))
}

// GenerateAll renders every supported harness in stable harness and name order.
func GenerateAll(c Catalog) ([]File, error) {
	var files []File
	for _, harness := range []Harness{Codex, OpenCode, Claude} {
		generated, err := Generate(c, harness)
		if err != nil {
			return nil, err
		}
		files = append(files, generated...)
	}
	return files, nil
}

func generateCodex(agent Agent, model string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s Re-run qbs sync to refresh.\n", generatedMarker)
	fmt.Fprintf(&b, "name = %s\n", tomlString(agent.Name))
	fmt.Fprintf(&b, "description = %s\n", tomlString(agent.Description))
	fmt.Fprintf(&b, "model = %s\n", tomlString(model))
	fmt.Fprintf(&b, "model_reasoning_effort = %s\n", tomlString(agent.Reasoning))
	fmt.Fprintf(&b, "sandbox_mode = %s\n", tomlString(agent.Permission))
	fmt.Fprintf(&b, "developer_instructions = %s\n", tomlString(promptWithSkills(agent)))
	return b.String()
}

func generateOpenCode(agent Agent, model string) string {
	permissions := map[string]string{
		"*":                  "deny",
		"read":               "deny",
		"list":               "deny",
		"glob":               "deny",
		"grep":               "deny",
		"lsp":                "deny",
		"bash":               "deny",
		"edit":               "deny",
		"webfetch":           "deny",
		"websearch":          "deny",
		"skill":              "deny",
		"external_directory": "deny",
		"task":               "deny",
	}
	for _, tool := range agent.Tools {
		for _, native := range openCodeTools(tool) {
			permissions[native] = "allow"
		}
	}
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "# %s Re-run qbs sync to refresh.\n", generatedMarker)
	fmt.Fprintf(&b, "description: %s\n", yamlString(agent.Description))
	b.WriteString("mode: subagent\n")
	fmt.Fprintf(&b, "model: %s\n", yamlString(model))
	fmt.Fprintf(&b, "reasoningEffort: %s\n", yamlString(agent.Reasoning))
	b.WriteString("permission:\n")
	permissionOrder := []string{"*", "read", "list", "glob", "grep", "lsp", "bash", "edit", "webfetch", "websearch", "skill", "external_directory", "task"}
	for _, name := range permissionOrder {
		if value, ok := permissions[name]; ok {
			fmt.Fprintf(&b, "  %s: %s\n", yamlString(name), value)
		}
	}
	b.WriteString("---\n\n")
	b.WriteString(promptWithSkills(agent))
	b.WriteByte('\n')
	return b.String()
}

func generateClaude(agent Agent, model string) string {
	var nativeTools []string
	for _, tool := range agent.Tools {
		nativeTools = append(nativeTools, claudeTools(tool)...)
	}
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "# %s Re-run qbs sync to refresh.\n", generatedMarker)
	fmt.Fprintf(&b, "name: %s\n", yamlString(agent.Name))
	fmt.Fprintf(&b, "description: %s\n", yamlString(agent.Description))
	if len(nativeTools) > 0 {
		fmt.Fprintf(&b, "tools: %s\n", strings.Join(nativeTools, ", "))
	}
	fmt.Fprintf(&b, "model: %s\n", yamlString(model))
	permissionMode := "plan"
	if agent.Permission == "workspace-write" {
		permissionMode = "acceptEdits"
	}
	fmt.Fprintf(&b, "permissionMode: %s\n", permissionMode)
	fmt.Fprintf(&b, "effort: %s\n", yamlString(agent.Reasoning))
	if len(agent.Skills) > 0 {
		b.WriteString("skills:\n")
		for _, skill := range agent.Skills {
			fmt.Fprintf(&b, "  - %s\n", yamlString(skill))
		}
	}
	if agent.Isolation == "worktree" {
		b.WriteString("isolation: worktree\n")
	}
	b.WriteString("---\n\n")
	b.WriteString(agent.Prompt)
	b.WriteByte('\n')
	return b.String()
}

func promptWithSkills(agent Agent) string {
	if len(agent.Skills) == 0 {
		return agent.Prompt
	}
	return fmt.Sprintf("Load and follow these skills before starting: %s.\n\n%s", strings.Join(agent.Skills, ", "), agent.Prompt)
}

func openCodeTools(tool string) []string {
	switch tool {
	case "read":
		return []string{"read", "list"}
	case "search":
		return []string{"glob", "grep", "lsp"}
	case "shell":
		return []string{"bash"}
	case "web":
		return []string{"webfetch", "websearch"}
	case "skills":
		return []string{"skill"}
	case "write":
		return []string{"edit"}
	default:
		return nil
	}
}

func claudeTools(tool string) []string {
	switch tool {
	case "read":
		return []string{"Read"}
	case "search":
		return []string{"Grep", "Glob"}
	case "shell":
		return []string{"Bash"}
	case "web":
		return []string{"WebFetch", "WebSearch"}
	case "skills":
		return []string{"Skill"}
	case "write":
		return []string{"Edit", "Write"}
	default:
		return nil
	}
}

func tomlString(value string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "\n", "\\n", "\r", "\\r", "\t", "\\t")
	return `"` + replacer.Replace(value) + `"`
}

func yamlString(value string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "\n", "\\n", "\r", "\\r", "\t", "\\t")
	return `"` + replacer.Replace(value) + `"`
}
