package agents

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"strings"
)

const generatedMarker = "Generated by qbs from its embedded agent catalog."

// Harness identifies one supported agent configuration format.
type Harness string

const (
	Codex    Harness = "codex"
	OpenCode Harness = "opencode"
	Claude   Harness = "claude"
)

// File is one generated path relative to the repository root.
type File struct {
	Path string
	Data []byte
}

// Generate renders all agents for a harness in stable name order.
func Generate(c Catalog, harness Harness) ([]File, error) {
	if err := c.Validate(); err != nil {
		return nil, err
	}
	agents := append([]Agent(nil), c.Agents...)
	sort.Slice(agents, func(i, j int) bool { return agents[i].Name < agents[j].Name })
	files := make([]File, 0, len(agents))
	for _, agent := range agents {
		profile := c.Models[agent.Model]
		var filePath, content string
		switch harness {
		case Codex:
			filePath = path.Join(".codex", "agents", agent.Name+".toml")
			content = generateCodex(agent, profile.Codex)
		case OpenCode:
			filePath = path.Join(".opencode", "agents", agent.Name+".md")
			content = generateOpenCode(agent, profile.OpenCode)
		case Claude:
			filePath = path.Join(".claude", "agents", agent.Name+".md")
			content = generateClaude(agent, profile.Claude)
		default:
			return nil, fmt.Errorf("generate agents: unsupported harness %q", harness)
		}
		files = append(files, File{Path: filePath, Data: []byte(content)})
	}
	return files, nil
}

// IsGenerated reports whether data belongs to QBS and may be refreshed safely.
func IsGenerated(data []byte) bool {
	marker := []byte("# " + generatedMarker)
	return bytes.HasPrefix(data, marker) || bytes.HasPrefix(data, append([]byte("---\n"), marker...))
}

// GenerateAll renders every supported harness in stable harness and name order.
func GenerateAll(c Catalog) ([]File, error) {
	var files []File
	for _, harness := range []Harness{Codex, OpenCode, Claude} {
		generated, err := Generate(c, harness)
		if err != nil {
			return nil, err
		}
		files = append(files, generated...)
	}
	return files, nil
}

func generateCodex(agent Agent, model string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s Re-run qbs init or qbs provision to refresh.\n", generatedMarker)
	fmt.Fprintf(&b, "name = %s\n", tomlString(agent.Name))
	fmt.Fprintf(&b, "description = %s\n", tomlString(agent.Description))
	fmt.Fprintf(&b, "model = %s\n", tomlString(model))
	fmt.Fprintf(&b, "model_reasoning_effort = %s\n", tomlString(agent.Reasoning))
	fmt.Fprintf(&b, "sandbox_mode = %s\n", tomlString(agent.Permission))
	fmt.Fprintf(&b, "developer_instructions = %s\n", tomlString(promptWithSkills(agent)))
	return b.String()
}

func generateOpenCode(agent Agent, model string) string {
	permissions := map[string]string{
		"*":                  "deny",
		"read":               "deny",
		"list":               "deny",
		"glob":               "deny",
		"grep":               "deny",
		"lsp":                "deny",
		"bash":               "deny",
		"edit":               "deny",
		"webfetch":           "deny",
		"websearch":          "deny",
		"skill":              "deny",
		"external_directory": "deny",
		"task":               "deny",
	}
	for _, tool := range agent.Tools {
		for _, native := range openCodeTools(tool) {
			permissions[native] = "allow"
		}
	}
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "# %s Re-run qbs init or qbs provision to refresh.\n", generatedMarker)
	fmt.Fprintf(&b, "description: %s\n", yamlString(agent.Description))
	b.WriteString("mode: subagent\n")
	fmt.Fprintf(&b, "model: %s\n", yamlString(model))
	fmt.Fprintf(&b, "reasoningEffort: %s\n", yamlString(agent.Reasoning))
	b.WriteString("permission:\n")
	permissionOrder := []string{"*", "read", "list", "glob", "grep", "lsp", "bash", "edit", "webfetch", "websearch", "skill", "external_directory", "task"}
	for _, name := range permissionOrder {
		if value, ok := permissions[name]; ok {
			fmt.Fprintf(&b, "  %s: %s\n", yamlString(name), value)
		}
	}
	b.WriteString("---\n\n")
	b.WriteString(promptWithSkills(agent))
	b.WriteByte('\n')
	return b.String()
}

func generateClaude(agent Agent, model string) string {
	var nativeTools []string
	for _, tool := range agent.Tools {
		nativeTools = append(nativeTools, claudeTools(tool)...)
	}
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "# %s Re-run qbs init or qbs provision to refresh.\n", generatedMarker)
	fmt.Fprintf(&b, "name: %s\n", yamlString(agent.Name))
	fmt.Fprintf(&b, "description: %s\n", yamlString(agent.Description))
	if len(nativeTools) > 0 {
		fmt.Fprintf(&b, "tools: %s\n", strings.Join(nativeTools, ", "))
	}
	fmt.Fprintf(&b, "model: %s\n", yamlString(model))
	permissionMode := "plan"
	if agent.Permission == "workspace-write" {
		permissionMode = "acceptEdits"
	}
	fmt.Fprintf(&b, "permissionMode: %s\n", permissionMode)
	fmt.Fprintf(&b, "effort: %s\n", yamlString(agent.Reasoning))
	if len(agent.Skills) > 0 {
		b.WriteString("skills:\n")
		for _, skill := range agent.Skills {
			fmt.Fprintf(&b, "  - %s\n", yamlString(skill))
		}
	}
	if agent.Isolation == "worktree" {
		b.WriteString("isolation: worktree\n")
	}
	b.WriteString("---\n\n")
	b.WriteString(agent.Prompt)
	b.WriteByte('\n')
	return b.String()
}

func promptWithSkills(agent Agent) string {
	if len(agent.Skills) == 0 {
		return agent.Prompt
	}
	return fmt.Sprintf("Load and follow these skills before starting: %s.\n\n%s", strings.Join(agent.Skills, ", "), agent.Prompt)
}

func openCodeTools(tool string) []string {
	switch tool {
	case "read":
		return []string{"read", "list"}
	case "search":
		return []string{"glob", "grep", "lsp"}
	case "shell":
		return []string{"bash"}
	case "web":
		return []string{"webfetch", "websearch"}
	case "skills":
		return []string{"skill"}
	case "write":
		return []string{"edit"}
	default:
		return nil
	}
}

func claudeTools(tool string) []string {
	switch tool {
	case "read":
		return []string{"Read"}
	case "search":
		return []string{"Grep", "Glob"}
	case "shell":
		return []string{"Bash"}
	case "web":
		return []string{"WebFetch", "WebSearch"}
	case "skills":
		return []string{"Skill"}
	case "write":
		return []string{"Edit", "Write"}
	default:
		return nil
	}
}

func tomlString(value string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "\n", "\\n", "\r", "\\r", "\t", "\\t")
	return `"` + replacer.Replace(value) + `"`
}

func yamlString(value string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "\n", "\\n", "\r", "\\r", "\t", "\\t")
	return `"` + replacer.Replace(value) + `"`
}
